[package]
name = "audioplayer"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[dependencies]
rodio = "0.16.0"
symphonia = "0.5.1"
